### ISSUE TITLE
Installing dynomite-manager on Openstack/KVM

### ISSUE THREAD

**Issue by nginxsantos** [Netflix/dynomite-manager#93] opened 2018-02-06 14:29 UTC
Hi,

Is it possible to install dynomite-manager on Openstack/KVM ? If so, is there any steps which we can refer ?

Thanks, Santos

**Comment by ipapapa** [comment] 2018-02-07 18:33
This seems to be a duplicate of https://github.com/Netflix/dynomite/issues/529

**Closed** 2018-02-07 18:34 UTC
